name: razorpay_flutter
description: Flutter plugin for Razorpay SDK. To know more about Razorpay, visit http://razorpay.com.
version: 2.0.0
homepage: https://github.com/razorpay/razorpay-flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  eventify: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.5

flutter:
  plugin:
    platforms:
      android:
        package: com.razorpay.razorpay_flutter
        pluginClass: RazorpayFlutterPlugin
      ios:
        pluginClass: RazorpayFlutterPlugin
